//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wigraf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wigraf.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Directory.
        /// </summary>
        internal static string i18nBrowseDirectory {
            get {
                return ResourceManager.GetString("i18nBrowseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening examples directory. Does it steal exist?.
        /// </summary>
        internal static string i18nExamplesOpenDirectoryErrorCaption {
            get {
                return ResourceManager.GetString("i18nExamplesOpenDirectoryErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples directory error.
        /// </summary>
        internal static string i18nExamplesOpenDirectoryErrorTitle {
            get {
                return ResourceManager.GetString("i18nExamplesOpenDirectoryErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening example. Does it steal exist?.
        /// </summary>
        internal static string i18nExamplesOpenErrorCaption {
            get {
                return ResourceManager.GetString("i18nExamplesOpenErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example error.
        /// </summary>
        internal static string i18nExamplesOpenErrorTitle {
            get {
                return ResourceManager.GetString("i18nExamplesOpenErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an attempt to access protected memory..
        /// </summary>
        internal static string i18nPreviewAccessErrorCaption {
            get {
                return ResourceManager.GetString("i18nPreviewAccessErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error.
        /// </summary>
        internal static string i18nPreviewAccessErrorTitle {
            get {
                return ResourceManager.GetString("i18nPreviewAccessErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview can not be created. Is WinGraphviz installed?.
        /// </summary>
        internal static string i18nPreviewInitErrorCaption {
            get {
                return ResourceManager.GetString("i18nPreviewInitErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization error.
        /// </summary>
        internal static string i18nPreviewInitErrorTitle {
            get {
                return ResourceManager.GetString("i18nPreviewInitErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct DOT code and try again.
        /// </summary>
        internal static string i18nPreviewParseErrorCaption {
            get {
                return ResourceManager.GetString("i18nPreviewParseErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse error.
        /// </summary>
        internal static string i18nPreviewParseErrorTitle {
            get {
                return ResourceManager.GetString("i18nPreviewParseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string i18nRefresh {
            get {
                return ResourceManager.GetString("i18nRefresh", resourceCulture);
            }
        }
    }
}
